[project]
name = "yt-dlp-dl"
version = "0.1.0"
description = "Use yt-dlp to download videos in global env by alias in Windows PowerShell"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "requests>=2.32.5",
    "uv>=0.9.28",
    "yt-dlp>=2025.12.8",
]
